"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: app
        image: your-docker-image:latest
        ports:
        - containerPort: 8000
"""
